[package]
name = "jointhedots"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
clap = "3.0.0-beta.4"
toml = "0.5"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

shellexpand = "2.1.0"
