name: Release

on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --release

      - name: Bundle release artifacts
        run: |
          mkdir release
          mv src/jtd-wrapper.sh release/jtd.sh
          mv target/release/jtd release/jtd

      - name: Ensure Cargo.toml version matches git tag

      - name: Publish to Crates.io
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: release/*
