name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Format
        run: cargo fmt -- --check
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy
